# Generated by Django 2.0.2 on 2018-02-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, ''), (1, 'FACEBOOK'), (2, 'TWITTER'), (3, 'LINKEDIN'), (4, 'MEDIUM'), (5, 'GITHUB')], default=0, verbose_name='link_type')),
                ('url', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.ManyToManyField(to='api.Link'),
        ),
    ]
