# Generated by Django 2.0.2 on 2018-03-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180320_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='job', verbose_name='imagem'),
        ),
    ]
