# Generated by Django 2.0.2 on 2018-02-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180214_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='links',
            field=models.ManyToManyField(related_name='projects', to='api.Link'),
        ),
    ]
