# Generated by Django 2.0.2 on 2018-03-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180320_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='', max_length=60, verbose_name='cargo'),
        ),
    ]
