# Generated by Django 2.0.2 on 2018-02-14 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180214_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='links',
        ),
        migrations.AddField(
            model_name='link',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
    ]
