# Generated by Django 2.0.2 on 2018-02-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180214_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.IntegerField(choices=[(0, ''), (1, 'FACEBOOK'), (2, 'TWITTER'), (3, 'LINKEDIN'), (4, 'MEDIUM'), (5, 'GITHUB'), (6, 'HEROKU'), (7, 'SITE')], default=0, verbose_name='link_type'),
        ),
    ]
