# Generated by Django 2.0.2 on 2018-02-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180214_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=100, verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='from_date',
            field=models.DateField(verbose_name='de'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='role',
            field=models.CharField(max_length=100, verbose_name='cargo'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='to_date',
            field=models.DateField(verbose_name='até'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=500, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.FileField(upload_to='job', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.IntegerField(choices=[(0, ''), (1, 'FACEBOOK'), (2, 'TWITTER'), (3, 'LINKEDIN'), (4, 'MEDIUM'), (5, 'GITHUB'), (6, 'HEROKU'), (7, 'SITE')], default=0, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='project', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
    ]
