# Generated by Django 2.0.2 on 2018-02-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_store',
            field=models.BooleanField(default=False, verbose_name='na loja'),
        ),
        migrations.AddField(
            model_name='job',
            name='link_store',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='link da loja'),
        ),
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='nome'),
        ),
    ]
