# Generated by Django 2.0.2 on 2018-02-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180216_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='categoria')),
                ('holder', models.CharField(max_length=100, verbose_name='titular')),
                ('date_conclusion', models.DateField(verbose_name='data de conclusão')),
                ('course', models.CharField(max_length=150, verbose_name='curso')),
                ('school', models.CharField(max_length=150, verbose_name='escola')),
            ],
        ),
    ]
