# Generated by Django 2.0.2 on 2018-03-11 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_certificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Certificado', 'verbose_name_plural': 'Certificados'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Experiência', 'verbose_name_plural': 'Experiências'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Trabalho', 'verbose_name_plural': 'Trabalhos'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Projetos', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Habilidade', 'verbose_name_plural': 'Habilidades'},
        ),
    ]
